# 2DV516, Python Lecture, Part 2: Numpy

Adapted by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

Further adapted and ported to Python3 by Rafael M. Martins for 2DV516 at Linnaeus University.

## Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

Some of you may have previous knowledge in Matlab, in which case we also recommend the numpy for Matlab users page (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).

In this tutorial, we will cover:

* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [3]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [4]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape)
print(a)
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,)
[1 2 3]
[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print("Array:")
print(b)
print("Shape:", b.shape)
print("Some elements:")
print(b[0, 0], b[1, 2])
print(b[0])

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Some elements:
1 6
[1 2 3]


Numpy also provides many other functions to create arrays:

In [9]:
z = np.zeros((2, 2, 2))  # Create an array of all zeros
print(z)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [12]:
np.ones((2,8))   # Create an array of all ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.full((2,2), 7) # Create a constant array

array([[7, 7],
       [7, 7]])

In [15]:
np.eye(3)        # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.randn(3, 4) # Create an array filled with random values

array([[-0.4118246 , -0.02011935,  0.29218993, -1.87942067],
       [-1.07417977,  0.13228767, -1.3253312 , -0.24626687],
       [-0.75025939, -0.43110957,  0.83841546,  1.52874149]])

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [21]:
import numpy as np

a = np.array([
    [1,2,3,4], 
    [5,6,7,8], 
    [9,10,11,12]])

# Slice the first 2 rows, and columns 1 to 3 (not included)
b = a[:2, 1:3]

print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [22]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a)

2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can also mix integer indexing with slice indexing. Also, a colon by itself means all rows/columns.

In [20]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [23]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [24]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [24]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int32


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [26]:
x = np.array([
    [1,2],
    [3,4]], dtype=np.float64)
y = np.array([
    [5,6],
    [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print("Same result:")
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
Same result:
[[ 6.  8.]
 [10. 12.]]


In [27]:
# Elementwise difference; both produce the array
print(x - y)
print("Same result:")
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
Same result:
[[-4. -4.]
 [-4. -4.]]


In [28]:
# Elementwise product; both produce the array
print(x * y)
print("Same result:")
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
Same result:
[[ 5. 12.]
 [21. 32.]]


In [29]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [31]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(y))

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[[19 22]
 [43 50]]
219
219
[29 67]
[29 67]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [33]:
x = np.array([
    [1,2],
    [3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Some other common examples are below:

In [42]:
print("log(x)")
print(np.log(x))
print()
print("mean and std. dev. of x (across all dim.)")
print(np.mean(x), np.std(x))
print()
print("x to the power of 5")
print(np.power(x, 5))
print()
print("min and max of x (across all dim.)")
print(np.min(x), np.max(x))

log(x)
[[0.         0.69314718]
 [1.09861229 1.38629436]]

mean and std. dev. of x (across all dim.)
2.5 1.118033988749895

x to the power of 5
[[   1   32]
 [ 243 1024]]

min and max of x (across all dim.)
1 4


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [45]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Broadcasting

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print x * 2

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [54]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros(shape=x.shape)   # Create an empty matrix with the same shape as x
print("x:")
print(x)
print("v:")
print(v)
print("y:")
print(y)

x:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
v:
[1 0 1]
y:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow.

Numpy broadcasting allows us to perform this computation like this, using broadcasting:

In [58]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these **rules**:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [59]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [79]:
# Add a vector to each column of a matrix
v = np.array([1,2,3,4])
print(v)
print(x)

# Initially, x and v are not compatible, because x is (4, 3) and v is (4,)
# When it is transposed, x becomes compatible with v with shape (3, 4)
# After the operation, we transpose again to match x's original shape
print("With transpose:")
print((x.T * v).T)

# Another solution is to reshape v instead (transposing doesn't work with 1-D vectors)
# The first argument (-1) means "as many rows as it fits"; the second (1) means "exactly 1 column"
print("With reshape (same result):")
print(x * v.reshape(-1, 1))

[1 2 3 4]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
With transpose:
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]
 [40 44 48]]
With reshape (same result):
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]
 [40 44 48]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.